
# CONEX\u00c3O COM MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/deosermis
spring.datasource.username=root
spring.datasource.password=

# DRIVER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# PORTA (opcional)
server.port=8080